### ISSUE TITLE
how to finetune 384x384 model

### ISSUE THREAD

**Issue by youngwanLEE** [mlpc-ucsd/CoaT#9]
Hi,

Could you share the script for finetuning 384x384 model?

**Comment by xwjabc** [comment]
Sure, I will release the related script this weekend.

**Comment by youngwanLEE** [comment]
@xwjabc Thanks for the quick response !! 

I have utilized your CoaT and Factorized Attention module, and I think it is very effective !! 👍 

Also, I'm very impressed by your effort to maintain this code. :)

**Comment by xwjabc** [comment]
Hi @youngwanLEE, I am sorry for the severe delay due to some of my personal affairs! I have recently added the fine-tuning script for 384x384 model. Feel free to try it out. 

In addition, since I am not available to access enough GPUs these days, I have not tried to reproduce the results (84.5%) using the updated fine-tuning script with the latest code in the repo. If you find that the results are not reproducible, please do not hesitate to point it out. I will try my best to help with any issues and hopefully get some computation resources to reproduce the results.

**Comment by youngwanLEE** [comment]
@xwjabc Thank your for the kind reply :)
